from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from importlib.util import find_spec
from pathlib import Path
from typing import Any

from ..config import AppConfig

INVALID_SESSION_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


def detect_playwright() -> bool:
    return find_spec("playwright") is not None


def init_session_state(config: AppConfig, session_name: str) -> dict[str, Any]:
    session_name = _normalize_session_name(session_name)
    sessions_dir = config.data_dir / "sessions" / session_name
    sessions_dir.mkdir(parents=True, exist_ok=True)

    state_path = sessions_dir / "state.json"
    created = False
    if not state_path.exists():
        created = True
        payload = {
            "session_name": session_name,
            "status": "placeholder",
            "created_at": _now_iso(),
            "updated_at": _now_iso(),
            "playwright_detected": detect_playwright(),
            "notes": "placeholder state generated by session-init; replace with real storage state later",
        }
        state_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    return {
        "session_name": session_name,
        "state_dir": str(sessions_dir),
        "state_path": str(state_path),
        "created": created,
        "playwright_detected": detect_playwright(),
    }


def _normalize_session_name(session_name: str) -> str:
    cleaned = session_name.strip()
    if not cleaned:
        raise ValueError("session_name must not be empty")
    cleaned = INVALID_SESSION_CHARS.sub("_", cleaned)
    cleaned = cleaned.rstrip(" .")
    if not cleaned:
        raise ValueError("session_name becomes empty after sanitization")
    return cleaned


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()
