from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


def run_download_job(job: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(job, dict):
        raise TypeError(f"job must be a dict, got {type(job).__name__}")

    output_path_value = job.get("output_path")
    if not output_path_value:
        raise ValueError("job is missing output_path")

    output_path = Path(output_path_value)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    payload = {
        "job_id": job.get("job_id"),
        "video_url": job.get("video_url"),
        "status": "success",
        "downloader": job.get("downloader", "stub"),
        "created_at": job.get("created_at"),
        "completed_at": _now_iso(),
        "note": "placeholder download generated by downloader_stub",
    }

    if output_path.suffix.lower() == ".txt":
        text = "\n".join(f"{key}: {value}" for key, value in payload.items()) + "\n"
        output_path.write_text(text, encoding="utf-8")
    else:
        output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    file_size = output_path.stat().st_size

    result = dict(job)
    result.update(
        {
            "status": "success",
            "file_size": file_size,
            "output_path": str(output_path),
            "completed_at": payload["completed_at"],
            "downloader": payload["downloader"],
        }
    )
    return result


def run_download_jobs(jobs: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    for job in jobs:
        results.append(run_download_job(job))
    return results


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="microseconds")
