from __future__ import annotations

from typing import Any, Mapping


VIDEO_FIT_VERSION = "video-fit.v1"


def analyze_video_fit(video_detail: dict, account_score: dict | None = None) -> dict:
    """Analyze whether a video is a good fit for the current account strategy.

    This is a rule-based, fully local heuristic that estimates how well a video
    aligns with the expected performance profile of a short-video account.

    Parameters
    ----------
    video_detail:
        Video payload. The function expects view/like/comment/share metrics to be
        available either directly on the object or under a nested ``metrics``
        mapping. Common aliases such as ``view_count`` / ``like_count`` are also
        supported.
    account_score:
        Optional account-level scoring payload. When provided, the function uses
        it as a soft prior to adjust the fit score. The payload may include a
        ``total_score`` field or any of the account score dimensions generated by
        the local analysis pipeline.

    Returns
    -------
    dict
        A structured result containing:

        - ``fit_score``: integer score from 0 to 100
        - ``fit_level``: one of ``high`` / ``medium`` / ``low``
        - ``diagnostics``: raw metric rates and supporting counters
        - ``strengths``: explainable positive signals
        - ``risks``: explainable negative signals
        - ``actions``: suggested next-step actions

    Notes
    -----
    - No external services or heavy third-party dependencies are used.
    - The output is intended to be easy to audit and evolve alongside the rest
      of the offline analysis pipeline.
    """

    detail = _ensure_mapping(video_detail)
    metrics = _extract_metrics(detail)
    views = _safe_int(metrics.get("view"))
    likes = _safe_int(metrics.get("like"))
    comments = _safe_int(metrics.get("comment"))
    shares = _safe_int(metrics.get("share"))

    like_rate = _rate(likes, views)
    comment_rate = _rate(comments, views)
    share_rate = _rate(shares, views)

    engagement_score = _score_engagement(like_rate=like_rate, comment_rate=comment_rate, share_rate=share_rate)
    volume_score = _score_volume(views)
    consistency_score = _score_consistency(metrics)
    account_prior = _score_account_prior(account_score)

    raw_score = (
        engagement_score * 0.58
        + volume_score * 0.18
        + consistency_score * 0.10
        + account_prior * 0.14
    )

    fit_score = _clamp_int(raw_score)
    fit_level = _fit_level(fit_score)

    strengths = _build_strengths(views=views, like_rate=like_rate, comment_rate=comment_rate, share_rate=share_rate, account_prior=account_prior)
    risks = _build_risks(views=views, like_rate=like_rate, comment_rate=comment_rate, share_rate=share_rate, account_prior=account_prior)
    actions = _build_actions(fit_score=fit_score, fit_level=fit_level, strengths=strengths, risks=risks)

    return {
        "version": VIDEO_FIT_VERSION,
        "fit_score": fit_score,
        "fit_level": fit_level,
        "diagnostics": {
            "view_count": views,
            "like_count": likes,
            "comment_count": comments,
            "share_count": shares,
            "like_rate": round(like_rate, 4),
            "comment_rate": round(comment_rate, 4),
            "share_rate": round(share_rate, 4),
            "engagement_score": engagement_score,
            "volume_score": volume_score,
            "consistency_score": consistency_score,
            "account_prior_score": account_prior,
        },
        "strengths": strengths,
        "risks": risks,
        "actions": actions,
    }


def batch_analyze_video_fit(items: list[dict]) -> dict:
    """Analyze a batch of videos and return item-level results plus a summary.

    Parameters
    ----------
    items:
        A list of video payloads. Each item may optionally contain an
        ``account_score`` mapping; otherwise the function analyzes the video in
        isolation.

    Returns
    -------
    dict
        A mapping with the following keys:

        - ``version``: analysis version string
        - ``total``: number of items processed
        - ``results``: list of item-level outputs
        - ``summary``: distribution and aggregate statistics
    """

    results: list[dict[str, Any]] = []
    distribution = {"high": 0, "medium": 0, "low": 0}
    score_sum = 0

    for index, raw_item in enumerate(items):
        item = _ensure_mapping(raw_item)
        video_detail = _extract_video_detail(item)
        account_score = _extract_account_score(item)
        result = analyze_video_fit(video_detail, account_score)
        result["index"] = index
        results.append(result)
        fit_level = result.get("fit_level", "low")
        distribution[fit_level] = distribution.get(fit_level, 0) + 1
        score_sum += _safe_int(result.get("fit_score"))

    total = len(results)
    average_score = round(score_sum / total, 2) if total else 0.0

    return {
        "version": VIDEO_FIT_VERSION,
        "total": total,
        "results": results,
        "summary": {
            "average_fit_score": average_score,
            "distribution": distribution,
            "high_ratio": round(distribution["high"] / total, 4) if total else 0.0,
            "medium_ratio": round(distribution["medium"] / total, 4) if total else 0.0,
            "low_ratio": round(distribution["low"] / total, 4) if total else 0.0,
        },
    }


def _extract_metrics(video_detail: Mapping[str, Any]) -> dict[str, int]:
    metrics = _ensure_mapping(video_detail.get("metrics"))

    aliases = {
        "view": ("view", "views", "view_count", "play_count", "play", "vv"),
        "like": ("like", "likes", "like_count", "digg_count", "heart_count"),
        "comment": ("comment", "comments", "comment_count", "reply_count"),
        "share": ("share", "shares", "share_count", "repost_count"),
    }

    normalized: dict[str, int] = {}
    for target, names in aliases.items():
        value = None
        for name in names:
            if name in metrics:
                value = metrics.get(name)
                break
            if name in video_detail:
                value = video_detail.get(name)
                break
        normalized[target] = _safe_int(value)
    return normalized


def _score_engagement(*, like_rate: float, comment_rate: float, share_rate: float) -> int:
    like_component = min(like_rate / 0.08, 1.0)
    comment_component = min(comment_rate / 0.012, 1.0)
    share_component = min(share_rate / 0.006, 1.0)
    score = 100.0 * (0.55 * like_component + 0.30 * comment_component + 0.15 * share_component)
    return _clamp_int(score)


def _score_volume(views: int) -> int:
    if views <= 0:
        return 0
    if views < 100:
        return 18
    if views < 500:
        return 40
    if views < 2000:
        return 65
    if views < 10000:
        return 82
    return 92


def _score_consistency(metrics: Mapping[str, Any]) -> int:
    observed = sum(1 for key in ("view", "like", "comment", "share") if _safe_int(metrics.get(key)) > 0)
    if observed >= 4:
        return 100
    if observed == 3:
        return 85
    if observed == 2:
        return 70
    if observed == 1:
        return 45
    return 0


def _score_account_prior(account_score: Mapping[str, Any] | None) -> int:
    account = _ensure_mapping(account_score)
    if not account:
        return 50

    score = None
    for key in ("total_score", "overall", "score", "fit_score"):
        if key in account:
            score = _safe_int(account.get(key))
            break
    if score is None:
        score = _safe_int(account.get("activity_score")) * 0.4
        score += _safe_int(account.get("execution_score")) * 0.3
        score += _safe_int(account.get("interaction_score")) * 0.2
        score += _safe_int(account.get("stability_score")) * 0.1
    return _clamp_int(score)


def _build_strengths(
    *,
    views: int,
    like_rate: float,
    comment_rate: float,
    share_rate: float,
    account_prior: int,
) -> list[str]:
    strengths: list[str] = []

    if views >= 1000:
        strengths.append("样本量较充足，适合用来判断内容真实表现。")
    elif views >= 100:
        strengths.append("当前观看量足以做初步规则判断。")
    else:
        strengths.append("尽管样本量偏小，但仍可作为早期方向观察。")

    if like_rate >= 0.08:
        strengths.append("点赞率较高，说明开头或整体内容吸引力不错。")
    if comment_rate >= 0.012:
        strengths.append("评论率较高，说明内容具备讨论或提问空间。")
    if share_rate >= 0.006:
        strengths.append("转发率较高，说明内容有传播或收藏分享价值。")
    if account_prior >= 75:
        strengths.append("账号侧基础分较高，视频与账号整体风格更容易协同放大。")

    return strengths or ["当前视频没有明显强特征，但可以继续跟踪同类样本。"]


def _build_risks(
    *,
    views: int,
    like_rate: float,
    comment_rate: float,
    share_rate: float,
    account_prior: int,
) -> list[str]:
    risks: list[str] = []

    if views < 50:
        risks.append("观看量过小，当前结论更偏早期信号，稳定性有限。")
    if like_rate < 0.03:
        risks.append("点赞率偏低，说明视频吸引力或封面/开头可能不足。")
    if comment_rate < 0.003:
        risks.append("评论率偏低，内容互动引导可能不够强。")
    if share_rate < 0.001:
        risks.append("转发率偏低，内容的传播点或外显价值不足。")
    if account_prior < 40:
        risks.append("账号侧基线较弱，单条视频的适配判断需要更谨慎。")

    return risks or ["暂未发现明显风险点。"]


def _build_actions(*, fit_score: int, fit_level: str, strengths: list[str], risks: list[str]) -> list[str]:
    actions: list[str] = []

    if fit_level == "high":
        actions.append("优先复制当前视频的选题、开头结构和节奏，形成同模板批量测试。")
        actions.append("保留现有账号风格，并围绕高表现点扩展相邻题材。")
    elif fit_level == "medium":
        actions.append("保留当前题材，但优先微调开头钩子、标题和评论引导。")
        actions.append("继续采样同类视频，确认是否是稳定适配而非偶然波动。")
    else:
        actions.append("先不要放大当前模板，优先调整选题、开头和前3秒信息密度。")
        actions.append("用 3 到 5 条对照视频验证哪些元素能抬升互动率。")

    if any("评论" in item for item in risks):
        actions.append("在结尾加入明确提问或二选一问题，提升评论触发率。")
    if any("转发" in item for item in risks):
        actions.append("补充更强的实用性、总结性或情绪共鸣点，提升传播性。")
    if any("点赞" in item for item in risks):
        actions.append("强化标题、封面和首屏节奏，缩短价值到达时间。")
    if fit_score >= 80:
        actions.append("把这条视频归为正样本，后续可用于模板沉淀。")

    if strengths and len(actions) < 3:
        actions.append("保留当前高分特征，优先观察是否在更多样本中稳定复现。")

    return actions


def _fit_level(score: int) -> str:
    if score >= 75:
        return "high"
    if score >= 45:
        return "medium"
    return "low"


def _extract_video_detail(item: Mapping[str, Any]) -> dict[str, Any]:
    for key in ("video_detail", "detail", "video", "item"):
        candidate = item.get(key)
        if isinstance(candidate, Mapping):
            return dict(candidate)
    return dict(item)


def _extract_account_score(item: Mapping[str, Any]) -> dict[str, Any] | None:
    for key in ("account_score", "score", "account"):
        candidate = item.get(key)
        if isinstance(candidate, Mapping):
            return dict(candidate)
    return None


def _ensure_mapping(value: Any) -> dict[str, Any]:
    if isinstance(value, Mapping):
        return dict(value)
    return {}


def _rate(numerator: int, denominator: int) -> float:
    if denominator <= 0:
        return 0.0
    return max(0.0, numerator / denominator)


def _safe_int(value: Any) -> int:
    if value is None:
        return 0
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        return 0


def _clamp_int(value: float) -> int:
    return max(0, min(100, int(round(value))))
